# -*- coding: utf-8 -*-
"""Birkbeck.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMlLXQ71q5BZC5-9_IaHxxD8b5OA6reA
"""

import re

def birkbeck():
  path = "./birkbeck.txt"

  birkbeck = {}

  with open(path) as f:
    full_list = f.readlines()

  for items in full_list:
    value = re.findall("\A[a-zA-Z]*", items)[0]
    key = str(re.findall("[a-zA-Z]*\n", items)[0]).replace("\n","")
    birkbeck[key] = value

  return birkbeck