# -*- coding: utf-8 -*-
"""dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1P-dCQiLgkskqtXpnkUx6mqBUq-akV7
"""

# Import the words from 

import nltk
nltk.download('words')
from nltk.corpus import words

def all_words(letter, length):
  word_list = words.words()

  if(letter == "" and length <= 0):
    return word_list
  elif(letter == "" and length > 0):
    final_list = []
    for word in word_list:
      if(len(word) == length):
        final_list.append(word)

    return final_list
  elif(letter != "" and length <= 0):
    final_list = []
    for word in word_list:
      if(word[0].lower() == letter.lower()):
        final_list.append(word)

    return final_list
  elif(letter != "" and length > 0):
    final_list = []
    for word in word_list:
      if(len(word) == length and word[0].lower() == letter.lower()):
        final_list.append(word)

    return final_list
  else:
    return []