# -*- coding: utf-8 -*-
"""successatk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t6eAOiDJ0ZGvPOvyd8SpqbiQFPoaEXpq
"""

def success_at_k(str1, k_list, k):
  flag = 0
  for i in range(min(len(k_list), k)):
    if(str1.lower() == k_list[i].lower()):
      flag = 1

  return flag